### ISSUE TITLE
Greenlight user creation fails on first run of playbook due to DB docker container not ready

### ISSUE THREAD

**Issue by moonlies** [ebbba-org/ansible-role-bigbluebutton#109]
I can not reproduce this on every machine, but i am running the role in a playbook for one VM, where the creation of initial greenlight users fails, because the postgreSQL docker container takes to much time to get going.
The role however runs smoothly, since the return message is not checked for a missing database. If you run the playbook a second time, the users are created just fine.

**Comment by EdJoPaTo** [comment]
Can confirm, this also happened to me but I thought it was a hiccup and havn't given it that much thought.

**Comment by BrutalBirdie** [comment]
Yea I know about this issue already.
I will have rework that part and see if [community.docker.docker_compose](https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_module.html#ansible-collections-community-docker-docker-compose-module) has a way to check if the container is ready.

**Comment by BrutalBirdie** [comment]
Maybe using https://www.postgresql.org/docs/9.3/app-pg-isready.html we could solve this issue.

**Comment by BrutalBirdie** [comment]
already solved
