### ISSUE TITLE
Monitoring installation fails with invalid docker-compose error

### ISSUE THREAD

**Issue by l3d00m** [ebbba-org/ansible-role-bigbluebutton#112]
Installing from 395585682f7b04fc3ff62ee00001b36b0276b56d with bbb monitoring enabled on a fresh ubuntu 18.04 gives the following error.
```
TASK [bigbluebutton : start monitoring] *******************************************************************************************************************************************************************************************
fatal: [root@schule-kompakt-bbb3.de]: FAILED! => {"changed": false, "msg": "Configuration error - The Compose file '/root/bbb-monitoring/docker-compose.yaml' is invalid because:\nvolumes.prometheus_data value Additional properties are not allowed ('grafana_data' was unexpected)"}
```

This is how the volume section of the generated docker-compose file looks like 
```
volumes:
    prometheus_data:
      grafana_data:
```

You can see that grafana_data is intended more than it should be. Since I'm very new to Ansible, I couldn't make out the cause for this, but I thought it would be worth reporting anyways.

Thanks for the great role!

**Comment by BrutalBirdie** [comment]
Ahhhh Yes! @Davka look at this!
This is the same behavior you had with your template nginx config (was it nginx? Some template).
I will have to test this but I believe that when the indentation of the `{}` is done it will interprete that as well.

Example:
```jinja2
{% if bbb_monitoring_all_in_one_prometheus or bbb_monitoring_all_in_one_grafana %}
volumes:
  {% if bbb_monitoring_all_in_one_prometheus %}
  prometheus_data:
  {% endif %}
  {% if bbb_monitoring_all_in_one_grafana %}
  grafana_data:
  {% endif %}
{% endif %}
```
This will results in this issue.
I believe if done this way
```jinja2
volumes:
{% if bbb_monitoring_all_in_one_prometheus %}
  prometheus_data:
{% endif %}
{% if bbb_monitoring_all_in_one_grafana %}
  grafana_data:
{% endif %}
{% endif %}
```
There would be no problem.

Thanks for reporting this @l3d00m !
