### ISSUE TITLE
IPv6 | NGINX: sipjsHackViaWs

### ISSUE THREAD

**Issue by BrutalBirdie** [ebbba-org/ansible-role-bigbluebutton#123]
https://github.com/ebbba-org/ansible-role-bigbluebutton/blob/83471e86d6ddf982cd7929fe71cdbbac87b8b8ad/tasks/bbb-html5.yml#L12-L18

@danimo thanks

> Das müsste man für dual stack auch noch so anpassen, dass nginx proxy_pass auf v6 macht, wenn v6 angefragt wird

**Comment by danimo** [comment]
See https://docs.bigbluebutton.org/2.2/troubleshooting.html#configure-bigbluebuttonfreeswitch-to-support-ipv6.

**Comment by BrutalBirdie** [comment]
Closed due to inactivity
