### ISSUE TITLE
Expand "create Greenlight users" to allow setting the provider

### ISSUE THREAD

**Issue by einhirn** [ebbba-org/ansible-role-bigbluebutton#135]
Hi,

https://github.com/ebbba-org/ansible-role-bigbluebutton/blob/a17a01393cfec76c52d6b62f18f84d1e5bdca935/tasks/greenlight.yml#L50

doesn't allow setting the `provider` field listed in `rake --tasks`-output:
```
rake user:create[name,email,password,role,provider]  # Creates a user account
```
I'd like to create an LDAP user account with "admin" role so I don't need to `UPDATE` something in Postgres after the role is done...

**Comment by BrutalBirdie** [comment]
Ohh I was not aware that this exists.

https://github.com/bigbluebutton/greenlight/blob/74cb620b1c63915b0d87456ff42d483315fec7db/lib/tasks/user.rake#L7-L14
The provider can also be something else like google, office365, twitter etc etc.

This could be a nice enhancement.
Does this really work? I never tested this :D

I also use Greenlight with LDAP but never head the need to create LDAP users while deploying the system.
I can understand the use behind that even with LDAP.
If you have a closed registration or invite only, it can be quite the hussle to invite all users, so I can understand the need for this.

**Comment by einhirn** [comment]
Yeah, no... Obviously it doesn't allow for what I wanted: A LDAP user in the "Admin" role. It seems that greenlight can either create an admin account (`admin:create` - without provider) or a user account (`user:create` with provider). Even if I specify "admin" as role, it won't work for some reason yet to be determined...

**Comment by BrutalBirdie** [comment]
Closed due to inactivity
