### ISSUE TITLE
Allow putting custom certs without copying them

### ISSUE THREAD

**Issue by DerDanilo** [ebbba-org/ansible-role-bigbluebutton#175]
**Is your feature request related to a problem? Please describe.**
When certificates are injected externally there is no option to just place them to the final cert location since the playbook just copies them from the own cert/key location. When using own cert/key vars/location the playbook copies those certs.

When own certs are not provided and lets encrypt is disabled self signed certs will be created. This is fine but there are situations where one doesn't want local LE nor a self signed cert.

**Describe the solution you'd like**
An option that allows placing own certs in the final destination, hence 'disable self signed', 'disable letsencrypt', 'disable copy certs'.

**Describe alternatives you've considered**
Placing the actual certs twice into the system. But this doesn't make sense. Though it works currently.

```
# bbb_ssl_cert: "/etc/letsencrypt/live/{{ bbb_hostname }}/fullchain.pem"
# bbb_ssl_key: "/etc/letsencrypt/live/{{ bbb_hostname }}/privkey.pem"
bbb_ssl_cert: "{{ bbb_own_cert }}"
bbb_ssl_key: "{{ bbb_own_key }}"
# These two variables below can be used to copy a local cert/key file to the target
# which then is used.
# Need to set `bbb_letsencrypt_enable: false` then
bbb_own_cert: "/etc/ssl/acme/domain.pem"
bbb_own_key: "/etc/ssl/acme/domain.pem"
```

**Additional context**
Enough said I hope.

Thanks!

**Comment by BrutalBirdie** [comment]
If I understood this issue right, please bear with me..
You want to use SSL/TLS but don't want to provide a Letsencrypt cert, own cert or self signed cert. Because `certificates are injected externally`.

In a sense like NGINX proxy for all BBB Server and only that proxy has the SSL/TLS Certs?
Could you please elaborate a bit more what the use-case is exactly?

**Comment by DerDanilo** [comment]
Sorry for not giving a clear example.  I try to give more background to explain it.

The actual goal is to be able to define the certificates in the configuration that will be used without any change or further handling by the ansible role itself. No copy task, no csr, no Let's Encrypt task, etc. The cert must be on the host already before the Ansible playbook is run.
Providing the cert location with the "custom" vars won't work as it's working currently since those certs are only copied when the Ansible deploys them. Not practical with automatic cert renewal that does not directly run on the BBB node.

## But how is the cert deployed?

### Short version

There is another node generating and managing certificates that pushes new or renewed certificates to the target server and restarts required services. Hence the "externally injected". 

### Long version

This description may be out of scope for this project but it explains a bit more why it should be possible to allow certs being pushed from external sources.

LE ACME --> Cert Manager Server (creates and holds certs) --> Deployment Script --> Target Server --> Deployment Hook (Copy Cert/Restart service)

- There is a central server that manages all let's encrypt certificates (cert manger). Those may be DNS based challenges or webbased, doesn't matter for this example.
- The central server pushes new certificates to whatever server one configures on the cert manager. I can also restart services, do config checks, make cert backups and allows rollback in case of an unhandled error.
- The cert manager also commits new certs and automatic generated deploy scripts into a private and locally hosted git repository (cert backup and history)
- And more stuff
- Using the awesome acme.sh
- Using Ansible to deploy and manage it all

---

I am happy to provide a merge request since this shouldn't be to hard to implement. But for that I would need to know if the certs are being used anywhere else than in the nginx config and if the whole bbb role itself relies on the default location for the certs somewhere else or if it just uses the vars.
Is there a hard coded location for the certs when using the bbb installer script as fallback solution in case that one needs to use that? (I am not planning on doing so, but it might be used by someone else).

Thanks!

**Comment by BrutalBirdie** [comment]
Closed due to inactivity

**Comment by DerDanilo** [comment]
Well, I was waiting for more input and there was none. :-/

**Comment by crosscodr** [comment]
Hi @DerDanilo, this problem was addressed in another issue/PR though.
Look at #246
