### ISSUE TITLE
Add to official documentation?

### ISSUE THREAD

**Issue by einhirn** [ebbba-org/ansible-role-bigbluebutton#176]
Hi,
I just saw in https://github.com/bigbluebutton/bigbluebutton.github.io/pull/282 that one can have a mention of playbooks available for installing BBB... Perhaps you also want to add a patch to the docs?

**Comment by BrutalBirdie** [comment]
But this role is already linked there.
https://github.com/bigbluebutton/bigbluebutton.github.io/blob/master/_posts/2.3/2021-05-01-install.md

Or did I miss something?

**Comment by einhirn** [comment]
Sorry, I didn't see/realize that the "n0emis" Link actually points here. So it's rather a question whether "eBBBa" wants more visibility... But as the role is already linked, I'll close this issue now.
