### ISSUE TITLE
[BUG] - Server IP

### ISSUE THREAD

**Issue by DerDanilo** [ebbba-org/ansible-role-bigbluebutton#177]
**Describe the bug**
Using the ansible var `"{{ ansible_default_ipv4.address }}"` is problematic since it has some dependencies which do not apply in some setups. e.g. when using additonal nics for the default route or LAN.

**To Reproduce**
Using `"{{ ansible_default_ipv4.address }}"` with additional NIC and additonal routes.

**Expected behavior**
Being able to define the public IP in a single var in the defaults main.yml.

**Ansible version**
not relevant

Suggestion:

Add the following var in the defaults main.yml and reference is in the whole playbook instead of the var `{{ ansible_default_ipv4.address }}` directly. This way it's easy to replace the public IP without the requirement to define a lot of vars in the host or group vars, which is overhead just because of the IP.

`bbb_public_ip: '{{ ansible_default_ipv4.address }}'`

Thanks!

**Comment by BrutalBirdie** [comment]
Closed due to inactivity
