### ISSUE TITLE
Support more greenlight smtp options

### ISSUE THREAD

**Issue by DerDanilo** [ebbba-org/ansible-role-bigbluebutton#178]
Missing vars:

```
SMTP_OPENSSL_VERIFY_MODE=none
SMTP_TLS=true
```

Should be something like this:
```
SMTP_TLS={{ bbb_greenlight_smtp.tls | default('') }}
SMTP_OPENSSL_VERIFY_MODE={{ bbb_greenlight_smtp.opensslverifymode | default('') }}
```

`SMTP_OPENSSL_VERIFY_MODE` should only appear when required, otherwise greenlight might have trouble working at all.

Sending via local postfix failed for some reason. Couldn't get it to work. Connecting to a noreply smtp account works fine though. But it requires that the above option can be defined.

From the inline greenlight env comments:

```
> #   enable SMTPS: SMTP over direct TLS connection; usually port 465
> #   SMTP_TLS=true
> #
> # If your mail server has a self-signed certificate, you'll also need to include the line below.
> # Please note that enable this presents its own security risks and should not be done unless necessary.
> #   SMTP_OPENSSL_VERIFY_MODE=none
> #
> 
```

Thanks!

**Comment by BrutalBirdie** [comment]
Closed due to inactivity
