### ISSUE TITLE
PR #134 - Destroyed the docker version no longer external possible

### ISSUE THREAD

**Issue by BrutalBirdie** [ebbba-org/ansible-role-bigbluebutton#195]
#134 

Why?
https://github.com/ebbba-org/ansible-role-bigbluebutton/blob/2b27b504ed228260c450d8eb69625d8ee1f7bd46/templates/monitoring/monitoring.nginx.j2#L1-L21

```
{% if bbb_monitoring_external %}
```
This does not account  for `bbb_monitoring_all_in_one_external`

**Comment by BrutalBirdie** [comment]
@wilkis3

**Comment by BrutalBirdie** [comment]
Never mind!
RTFM! Get out of here!

**Comment by crosscodr** [comment]
Nevertheless, @wilkis3 can you remove `bbb_monitoring_all_in_one_external` from defaults/main.yml and make an entry in checkvars for this?
