### ISSUE TITLE
[BUG] "Check for running meetings" queries old server with same hostname

### ISSUE THREAD

**Issue by wansing** [ebbba-org/ansible-role-bigbluebutton#213]
**Describe the bug**
I can't set up a new BBB server for an existing hostname. [`check-for-sessions.yml`](https://github.com/ebbba-org/ansible-role-bigbluebutton/blob/bbb/2.3/tasks/check-for-sessions.yml) fails because queries `bbb_hostname`, which still points to the old server. Would it be possible to query 127.0.0.1 for running meetings instead?

**To Reproduce**
1. run an old bbb server (e.g. Ubuntu 16.04) on example.com
2. prepare a new server (e.g. Ubuntu 18.04) for exampe.com while the old server is still in use

**Expected behavior**
It should work.

**Ansible version**
```bash
ansible --version
ansible 2.9.23
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Feb 27 2021, 15:10:58) [GCC 7.5.0]
```

**Comment by BrutalBirdie** [comment]
Are you trying to upgrade from a 2.2 instance to 2.3?
Because that is not supported and will not be supported! Even BBB them self advise against doing that.

Rebuild the server to 18.04 LTS and then deploy.

**Comment by BrutalBirdie** [comment]
Maybe we should add this information to the README as well.
We had this information in the initial release for 2.3.0

https://github.com/ebbba-org/ansible-role-bigbluebutton/releases/tag/v2.3.0-a1.0.0

**Comment by wansing** [comment]
> Are you trying to upgrade from a 2.2 instance to 2.3?

No. But I'm setting up the new server while the old one is still running, in order to keep the downtime low and just switch when the new one is ready. My workaround for this issue was to replace `bbb_hostname` by `127.0.0.1` in `check-for-sessions.yml`.

**Comment by BrutalBirdie** [comment]
do you use a loadbalancer?
This way you could create the new server with a temporary new domain and after the setup switch them out.

**Comment by wansing** [comment]
Not really a load balancer, but a reverse proxy. Anyway, setting up the new server on a temporary new domain sounds like a great idea. When everything works, one can just change the domain and run the playbook again. (That's also easier for letsencrypt.)

Thank you very much! Feel free to close this issue, or to keep it open as a reminder to add it to the docs.

**Comment by BrutalBirdie** [comment]
Honestly I know way to little about your setup.
From what I imagine right now it would be best to just do this at night.

Many users of this role see BigBlueButton servers as temporary nodes in a cluster setup.
We also created a simple scalelite role https://github.com/ebbba-org/ansible-role-scalelite

If you wanna chat about all that you can also find us on Matrix.
This is my id `@brutalbirdie:matrix.org` and our big main channel is `#bigbluebutton-de:matrix.org` and there is also a smaller channel for ansible development only.
