### ISSUE TITLE
ufw rules are not reset after rerunnning the play

### ISSUE THREAD

**Issue by d3hof** [ebbba-org/ansible-role-bigbluebutton#220]
**Describe the bug**
ufw rules are not reset when rerunning the play as mentioned here #217 

**To Reproduce**
1. Run the playbook once with coturn_enabled: true
2. Rerun it again with coturn_enabled: false
3. Coturn ufw rules are still there

**Expected behavior**
ufw rules should be reset with every run

**Ansible version**
  ansible 2.10.12
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/d3h/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]

**Comment by BrutalBirdie** [comment]
we should remove greenlight and coturn from this role anyway.
This will be the task to fix this issue.
Closing this issue for now.
