### ISSUE TITLE
Alternative hostname for the certificate

### ISSUE THREAD

**Issue by edlerd** [ebbba-org/ansible-role-bigbluebutton#230]
It would be useful to specify alternative domains in order to have certbot generate for various subdomains. I.e. the bbb_hostname is bbb.example.org and the cert should also be valid on example.org

Provide a new, optional parameter additional_cert_hostname that can be set to example.org or other (sub)domains. Those additional ones are forwarded to certbot -d in https://github.com/ebbba-org/ansible-role-bigbluebutton/blob/7900bc196a028e2f899b47d7a0461573e439f58b/tasks/letsencrypt.yml#L28

**Comment by crosscodr** [comment]
Hi @edlerd, could you provide a Pull-Request for this?

**Comment by BrutalBirdie** [comment]
Closed due to inactivity
