### ISSUE TITLE
firewall  ufw (and firewalld)

### ISSUE THREAD

**Issue by genofire** [ebbba-org/ansible-role-bigbluebutton#24]
It would be nice to open firewall rules automatically (the known ports are at this rule).

Here are the ansible-modules:
- [ufw](https://docs.ansible.com/ansible/latest/modules/ufw_module.html)
- [firewalld](https://docs.ansible.com/ansible/latest/modules/firewalld_module.html)

Maybe we should detect, which firewall is running on the server, to use the correct ansible-module.

**Comment by BrutalBirdie** [comment]
I will create the first steps for `ufw` since `ufw` is also used by the [bbb-install](https://github.com/bigbluebutton/bbb-install)
