### ISSUE TITLE
[BUG] - Let's encrypt cert generation failure

### ISSUE THREAD

**Issue by ChrisKar96** [ebbba-org/ansible-role-bigbluebutton#259]
**Describe the bug**
Trying to acquire a TLS cert from certbot results in
stderr: |-
    Saving debug log to /var/log/letsencrypt/letsencrypt.log
    Plugins selected: Authenticator nginx, Installer nginx
    Obtaining a new certificate
    live directory exists for { domain }

The problem occurs when running the task `Generate or renew certificate with certbot`.
Most probably because of the task `Ensure target directory exists` that runs beforehand and creates the `/etc/letsencrypt/live/{ domain }` directory.

Subsequent runs of the playbook (and more specifically the 'tls' tag) results in the task `Ensure bbb_ssl_cert exists` failing with:
fatal: [bbb1.ellak.gr]: FAILED! => changed=false
  msg: file (/etc/letsencrypt/live/{ domain }/fullchain.pem) is absent, cannot continue
  path: /etc/letsencrypt/live/{ domain }/fullchain.pem
  state: absent

And the directory /etc/letsencrypt/live/{ domain }-001 gets created instead.

This behavior was introduced with the merge of #246. 
The fix should be to remove the task `Ensure target directory exists` from `tasks/certificate.yml` and (if needed) add it in `tasks/certificate-custom.yml`

**Ansible version**
ansible 2.10.6
  config file = None
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/.local/lib/python3.7/site-packages/ansible
  executable location = /home/ansible/.local/bin/ansible
  python version = 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]

**Comment by crosscodr** [comment]
Hi @ChrisKar96,
Interesting behavior of letsencrypt. I don't use it, so I have to ask:
Let's assume the ssl-target-directory does not exist. Then, in a first run, letsencrypt would create it and put certs into it. Will it fail after that in a subsequent ansible-run also, since the directory is existing now?

**Comment by ChrisKar96** [comment]
The certificate-letsencrypt task runs a certbot command, so I'm absolutely positive that it will not fail in subsequent runs. That said, my tests for submitting this issue resulted in my domain getting rate limited some days by letsencrypt, so I haven't been able to test my solution yet. I submitted the untested PR that probably fixes the behavior of letsencrypt and I will need a review from someone who uses external certs, to be sure that fixing one functionality doesn't break the other.

**Comment by defnull** [comment]
I quess that certbot assumes that its config must be present in the directory if the directory itself exists. That would make sense and explain the behavior. So, no directory is fine (first run) and a directory with config is also fine (subsequent run) but directory without config is an error.
