### ISSUE TITLE
[BUG] - bbb_meteor default "{}"

### ISSUE THREAD

**Issue by olwe0002** [ebbba-org/ansible-role-bigbluebutton#271]
**Describe the bug**
the override file `/etc/bigbluebutton/bbb-html5.yml` is a yaml file. But the the [default](https://github.com/ebbba-org/ansible-role-bigbluebutton/blob/bbb/2.3/defaults/main.yml#L77) value for bbb_meteor, also in tasks [here](https://github.com/ebbba-org/ansible-role-bigbluebutton/blob/bbb/2.3/tasks/bbb-html5.yml#L17) and [here](https://github.com/ebbba-org/ansible-role-bigbluebutton/blob/bbb/2.3/tasks/bbb-html5.yml#L25) is the value `{}`, which isn't a valid yaml value. The result is that this value is written into `/etc/bigbluebutton/bbb-html5.yml` and breaks at least the config check output.

**To Reproduce**
1. don't set `bbb_meteor` variable so that the default value is used
2. run the installation
3. check the content of the `/etc/bigbluebutton/bbb-html5.yml` file on the server, it is `{}`
4. run `bbb-conf --check`
result:
```
/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
/etc/bigbluebutton/bbb-html5.yml (HTML5 client config override)
                             build: 
                        kurentoUrl: 
                  enableListenOnly: 
                    sipjsHackViaWs: 
```

**Expected behavior**

```
/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
/etc/bigbluebutton/bbb-html5.yml (HTML5 client config override)
                             build: 1854
                        kurentoUrl: wss://your-url-here/bbb-webrtc-sfu
                  enableListenOnly: true
                    sipjsHackViaWs: false
```

**Comment by defnull** [comment]
But `{}` **is** a valid yaml value. It's an empty hash. There is no other way to represent an empty hash in yaml.

**Comment by crosscodr** [comment]
Hi @olwe0002, good catch!
I thought this can easily be fixed by adding `| default()` in the first task of bbb-html5.yml and not defining bbb_meteor in defaults.
But it turns out, that even then the `to_nice_yaml` filter prints `''` to bbb-html5.yml which confuses bbb-conf --check.

**Comment by crosscodr** [comment]
Hi @defnull, thank you for your thoughts on this.
So it may be just an error of `bbb-conf --check` and should be fixed there.

**Comment by BrutalBirdie** [comment]
I mean... we could change the default of [bbb_meteor](https://github.com/ebbba-org/ansible-role-bigbluebutton/blob/953a6c910bcac9afd91415b5a3c4d18b31c01ceb/defaults/main.yml#L77) to a filled out example, if you will best practice and the issue would be... solved?
:)

**Comment by crosscodr** [comment]
Maybe like so:
```
bbb_meteor:
  public:
    media:
      sipjsHackViaWs: true
```
Btw. is this needed in 2.4 anyway?

**Comment by BrutalBirdie** [comment]
I am not sure about that.

**Comment by crosscodr** [comment]
From what I have heard about BBB 2.4, the sipjs-hack is still needed. We could use it as default.
