### ISSUE TITLE
Remove Greenlight and move into a separate Role

### ISSUE THREAD

**Issue by BrutalBirdie** [ebbba-org/ansible-role-bigbluebutton#272]
Greenlight is used for BigBlueButton but does not belong to BigBlueButton by default.
This should be in its own Role.

**Comment by crosscodr** [comment]
Hi @BrutalBirdie if you search for a greenlight role, you can use this one https://github.com/crosscodr/ansible-role-greenlight.
Some of the recent changes in ebbba.biglbuebutton were also transferred to this role.
