### ISSUE TITLE
Remove Coturn and move into a separate Role

### ISSUE THREAD

**Issue by BrutalBirdie** [ebbba-org/ansible-role-bigbluebutton#273]
Coturn is used for BigBlueButton but does not belong to BigBlueButton by default.
This should be in its own Role.

**Comment by cherbst** [comment]
As coturn is now included in official BigBlueButton installation (https://docs.bigbluebutton.org/administration/turn-server/), how does this affect this role? Is there an option so that the standard installation can be used or is an external coturn instance necessary?
