### ISSUE TITLE
Allow to use virtual backgrounds easily

### ISSUE THREAD

**Issue by kaystrobach** [ebbba-org/ansible-role-bigbluebutton#285]
**Is your feature request related to a problem? Please describe.**

Would be nice to have an easy way to replace / add virtuall backgrounds

**Describe the solution you'd like**

* define a folder which images
* upload images
* convert them

**Describe alternatives you've considered**

* custom role

**Additional context**

* https://docs.bigbluebutton.org/2.4/new.html#webcam-background-blur
* https://docs.bigbluebutton.org/admin/customize.html#use-custom-images-for-virtual-background

Imho this includes a merge of the image names with the following option in the playbook:

```
      bbb_meteor:
        virtualBackgrounds:
          fileNames:
```

**Comment by BrutalBirdie** [comment]
Talked to @Davka about this, we are looking into it.

**Comment by einhirn** [comment]
I am using the list from the filenames in the meteor config to copy the files and the thumbnails to the servers in my custom role. Could perhaps contribute that, although it's no rocket science.

We're still preparing the thumbnails manually - you need to put the images there anyway, so you can also fix the thumbnails...
Of course you could add a dependency to eg. imageMagick or something to automate it, but is it really worth the additional hassle?

**Comment by dmtrhfr** [comment]
I am working on a solution https://github.com/ebbba-org/ansible-role-bigbluebutton/pull/336

**Comment by kaystrobach** [comment]
We are doing it for that way now as well. With the 2.6 option to upload custom images the importance gets  lower imho

**Comment by dmtrhfr** [comment]
> We are doing it for that way now as well. With the 2.6 option to upload custom images the importance gets lower imho

Not sure about that. We host for Organisations that are not interested in uploading custom backgrounds at all. They just want some branded backgrounds.

**Comment by BrutalBirdie** [comment]
Default feature in 2.6.

**Comment by defnull** [comment]
Would still be nice to have a way to deploy custom default backgrounds that are available to all users. Please re-open?
