### ISSUE TITLE
Upgrade from 2.3 to 2.4 fails

### ISSUE THREAD

**Issue by Davka** [ebbba-org/ansible-role-bigbluebutton#304]
**Describe the bug**
When updating from a 2.3, it can happen that the NGINX cannot start because the load balancer configuration is not yet available at the time.

**To Reproduce**
Upgrade from 2.3 to latest 2.4 using this role

**Comment by defnull** [comment]
Upgrading anything but patch releases is discouraged. There are _lots_ of places where this can go wrong. I'd always install on a fresh Ubuntu if possible.

**Comment by BrutalBirdie** [comment]
I did not have this issue when upgrading aprox 10x 2.3 Servers to 2.4.
Strange.
