### ISSUE TITLE
role will fail when systemd-timesyncd is already disabled

### ISSUE THREAD

**Issue by Davka** [ebbba-org/ansible-role-bigbluebutton#309]
**Describe the bug**
For example, if you use a VM template in which systemd-timesyncd is already disabled or removed, the role will fail

```
Unable to enable service systemd-timesyncd: Failed to enable unit: Unit file /etc/systemd/system/systemd-timesyncd.service is masked.
```

```
"Could not find the requested service systemd-timesyncd
```

**To Reproduce**
Use a VM template where the service is masked or uninstalled

**Comment by defnull** [comment]
This is the case for the official ubuntu:20.04 lxd image.
