### ISSUE TITLE
Option to use mongodb3 from Ubuntu repos

### ISSUE THREAD

**Issue by singpolyma** [ebbba-org/ansible-role-bigbluebutton#328]
**Is your feature request related to a problem? Please describe.**

MongoDB 4 from upstream is not open source, under SSPL, a license which many orgs do not allow use of.

**Describe the solution you'd like**

I have tested with manually removing the mongodb apt source and uninstalling then just installing mongodb from the Ubuntu repositories.  This works fine and solves the problem.

**Comment by BrutalBirdie** [comment]
BBB 2.6 uses mongodb4. Closing.

**Comment by defnull** [comment]
More words: The official BBB install script depends on MongoDB 4.4 (see https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install-2.6.sh#L305) and this ansible role tries to stay as close as possible to whatever the BBB maintainers recommend. Deviating too much would make support and debugging more difficult. BBB is a complicated system, it can break in very unexpected ways. If you believe that an early fork of MongoDB is sufficient, please get in contact with the BBB maintainers directly so the change can be verified and properly tested. 

That said, let me quote the [SSPL FAQ](https://www.mongodb.com/licensing/server-side-public-license/faq):

> The copyleft condition of Section 13 of the SSPL applies only when you are offering the functionality of MongoDB, or modified versions of MongoDB, to third parties as a service. There is no copyleft condition for other SaaS applications that use MongoDB as a database.

Section 13 does not apply to the use of MongoDB in BBB, even if you offer BBB as a service.
