### ISSUE TITLE
Fix Ansible-Lint?

### ISSUE THREAD

**Issue by einhirn** [ebbba-org/ansible-role-bigbluebutton#340]
IDK, maybe it will improve something?

Would probably mean a lot of little changes (lower to uppercase, whitespace etc.).

But some things reported as errors would need more effort - there are places where we use vars as arguments for "state" etc. which the linter does not like at all. Probably we'd need to configure linting exclusions there?

**Comment by BrutalBirdie** [comment]
Fixed +1
