### ISSUE TITLE
[BUG] - BBB 2.6.14 needs Node 18

### ISSUE THREAD

**Issue by defnull** [ebbba-org/ansible-role-bigbluebutton#367]
**Describe the bug**
BBB 2.6.14 changed the required node version from 16 to 18 (yes, in a patch release). The defaults for the role should reflect that.

Oh, and Java 11 to 17. That's currently hard-coded in the role.

**Comment by BrutalBirdie** [comment]
The v2.6.14 tag has node as 18 / master branch as well:
https://github.com/ebbba-org/ansible-role-bigbluebutton/blob/d40f0a003bc48c0dd539d7853fc08a06e8c28d95/defaults/main.yml#L313

With the Java version same with the v2.6.14 tag and master branch but true it is hard coded:
https://github.com/ebbba-org/ansible-role-bigbluebutton/blob/d40f0a003bc48c0dd539d7853fc08a06e8c28d95/vars/main.yml#L12

**Comment by defnull** [comment]
Ahh, got bitten by the branch vs tag issue again. The bbb/2.6 branch does not contain those fixes.
