### ISSUE TITLE
Add a scheduled backup task

### ISSUE THREAD

**Issue by anadahz** [ebbba-org/ansible-role-bigbluebutton#37]
This issue is about adding support for scheduled BBB backups.

The following parts should be included in the backup (I hope I'm not missing anything):

- Greenlight
- PostgreSQL DB
- Recordings (optional)

**Comment by n0emis** [comment]
I am not sure if this would blow up the role too much, but I would ot block such a contribution.

**Comment by BrutalBirdie** [comment]
Some would argue a simple backup feature which backups this stuff to `/backup` with 1 week retention policy would be enough.
But backups on the same drive...

Also when implementing such a feature, what solution for backup do you use to make the users happy?
Restic, Borg, Duplicacy?  yada yada yada

I believe this suggested enhancement is understandable but to much for this role.

Just checkout the Ansible Galaxy for Backup roles:
https://galaxy.ansible.com/search?deprecated=false&keywords=backup&order_by=-relevance&page=1

**Comment by EdJoPaTo** [comment]
Putting backups into a single location other user dependent stuff can easily pull/push backups into their backup place of choice way easier.

**Comment by BrutalBirdie** [comment]
I've decided against this.
The only backup worthy data of a BBB Server might be greenlight if used and the recordings.
Also recordings are a special case when using a cluster setup of BBB.
There is enough out there to do this the right way for each use-case.
