### ISSUE TITLE
[BUG] - bbb_exporter failes because of missing mounting (bbb/2.7)

### ISSUE THREAD

**Issue by berott** [ebbba-org/ansible-role-bigbluebutton#373]
The installation of `bbb_exporter` fails on bbb/2.7 because https://github.com/ebbba-org/ansible-role-bigbluebutton/commit/c31be1e7ae1aa25472f115fc7ace46ddf8d19a8c is only on the master.

Is it possible to merge the master in bbb/2.7?

**Comment by BrutalBirdie** [comment]
Fixed
