### ISSUE TITLE
sendmail not working in greenlight docker?

### ISSUE THREAD

**Issue by DO1JLR** [ebbba-org/ansible-role-bigbluebutton#38]
It looks like the sendmail in the greenlight docker container is not working properly. At least it is not able to send confirmation mails. And a tcpdump on the big blue button server shows no smtp traffic.

I tested it with the ``site.yml`` playbook and the configuration from [this git repository](https://github.com/DO1JLR/testing_bbb-and-livestreaming/tree/624c0b308f8a327a89bfd0fc497be21b0e37e84e).

In the docker container, when I run sendmail, I received the following message:
```
bash-4.4# echo "Subject: sendmail test" | sendmail -v l3d@c3woc.de
sendmail: can't connect to remote host (127.0.0.1): Connection refused
```

are there **sendmail experts who can help here?**

**Comment by n0emis** [comment]
Can this issue be closed?

**Comment by DO1JLR** [comment]
the issue is not resolved, I guess.

but I can deal with the workaround. And for the greenlight docker container, I think this is also the wrong place.

**Comment by edlerd** [comment]
Could solve sending email by installing postfix.

Additional steps to configure postfix in /etc/postfix/main.cnf needed were:
- and the docker ip range 172.18.0.0/16 to mynetworks
- point to the letsencrypt certificates that are created by the bbb role

hostname must match the fqdn.

Maybe should add postfix on the host and configure it within the role?

**Comment by BrutalBirdie** [comment]
> Could solve sending email by installing postfix.
> 
> Additional steps to configure postfix in /etc/postfix/main.cnf needed were:
> 
>     * and the docker ip range 172.18.0.0/16 to mynetworks
> 
>     * point to the letsencrypt certificates that are created by the bbb role
> 
> 
> hostname must match the fqdn.
> 
> Maybe should add postfix on the host and configure it within the role?

@edlerd would you be able to do this as a PR since you have solved it already once?

Closing the issue for now since this is stale since 21.12.2020
