### ISSUE TITLE
Increase nginx server_names_hash_bucket_size

### ISSUE THREAD

**Issue by Orilcious** [ebbba-org/ansible-role-bigbluebutton#85]
Hello,

great playbook, worked quite well.
I can maybe contribute a little enhancement.

The default nginx server_names_hash_bucket_size is 32.
This caused the last few jobs of the setup to fail in my usecase.

Do you think it would enhance the playbook to echo "server_names_hash_bucket_size 64;" into /etc/nginx/nginx.conf after installing nginx and before starting and enabling it?

Kind regards,
Ori

**Comment by BrutalBirdie** [comment]
@Orilcious this should be a simple PR would you be able to do this?

**Comment by BrutalBirdie** [comment]
Closed due to inactivity
