### ISSUE TITLE
LetsEncrypt Staging Server

### ISSUE THREAD

**Issue by Nuxij** [ebbba-org/ansible-role-bigbluebutton#86]
Would it be possible to have an option to switch to the LE staging server? This would aid in avoiding the rate limits while testing deployment.

**Comment by BrutalBirdie** [comment]
Yea that would be awesome! Will check that.

**Comment by n0emis** [comment]
I would rather prefer an option, to set a custom acme-api. this would enable user to also use different CAs

**Comment by BrutalBirdie** [comment]
Solved via merge of #106 

# CLOSED
