### ISSUE TITLE
WebRTC seems to advertise internal docker IP addresses

### ISSUE THREAD

**Issue by felinira** [ebbba-org/ansible-role-bigbluebutton#94]
Checking about:webrtc on Firefox shows me internal docker IPs like 172.18.0.1. This is a problem when combined with a turn server that rejects those IPs. It also makes the echo test take longer.

**Comment by felinira** [comment]
I added a PR to fix the issue. Kurento was probably confused and listened on the docker interface

**Comment by ChrisKar96** [comment]
Since #201 was merged, I think this can be closed now.

**Comment by BrutalBirdie** [comment]
Closed due to inactivity
